/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as IskolankrolRouteImport } from './routes/iskolankrol'
import { Route as HirekRouteImport } from './routes/hirek'
import { Route as DokumentumtarRouteImport } from './routes/dokumentumtar'
import { Route as BuszkesegeinkRouteImport } from './routes/buszkesegeink'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const IskolankrolRoute = IskolankrolRouteImport.update({
  id: '/iskolankrol',
  path: '/iskolankrol',
  getParentRoute: () => rootRouteImport,
} as any)
const HirekRoute = HirekRouteImport.update({
  id: '/hirek',
  path: '/hirek',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentumtarRoute = DokumentumtarRouteImport.update({
  id: '/dokumentumtar',
  path: '/dokumentumtar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuszkesegeinkRoute = BuszkesegeinkRouteImport.update({
  id: '/buszkesegeink',
  path: '/buszkesegeink',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buszkesegeink': typeof BuszkesegeinkRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buszkesegeink': typeof BuszkesegeinkRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/buszkesegeink': typeof BuszkesegeinkRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buszkesegeink'
    | '/dokumentumtar'
    | '/hirek'
    | '/iskolankrol'
    | '/kapcsolat'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buszkesegeink'
    | '/dokumentumtar'
    | '/hirek'
    | '/iskolankrol'
    | '/kapcsolat'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buszkesegeink'
    | '/dokumentumtar'
    | '/hirek'
    | '/iskolankrol'
    | '/kapcsolat'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuszkesegeinkRoute: typeof BuszkesegeinkRoute
  DokumentumtarRoute: typeof DokumentumtarRoute
  HirekRoute: typeof HirekRoute
  IskolankrolRoute: typeof IskolankrolRoute
  KapcsolatRoute: typeof KapcsolatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iskolankrol': {
      id: '/iskolankrol'
      path: '/iskolankrol'
      fullPath: '/iskolankrol'
      preLoaderRoute: typeof IskolankrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hirek': {
      id: '/hirek'
      path: '/hirek'
      fullPath: '/hirek'
      preLoaderRoute: typeof HirekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumentumtar': {
      id: '/dokumentumtar'
      path: '/dokumentumtar'
      fullPath: '/dokumentumtar'
      preLoaderRoute: typeof DokumentumtarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buszkesegeink': {
      id: '/buszkesegeink'
      path: '/buszkesegeink'
      fullPath: '/buszkesegeink'
      preLoaderRoute: typeof BuszkesegeinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuszkesegeinkRoute: BuszkesegeinkRoute,
  DokumentumtarRoute: DokumentumtarRoute,
  HirekRoute: HirekRoute,
  IskolankrolRoute: IskolankrolRoute,
  KapcsolatRoute: KapcsolatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
