/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IskolankrolRouteImport } from './routes/iskolankrol'
import { Route as HirekRouteImport } from './routes/hirek'
import { Route as DokumentumtarRouteImport } from './routes/dokumentumtar'
import { Route as IndexRouteImport } from './routes/index'

const IskolankrolRoute = IskolankrolRouteImport.update({
  id: '/iskolankrol',
  path: '/iskolankrol',
  getParentRoute: () => rootRouteImport,
} as any)
const HirekRoute = HirekRouteImport.update({
  id: '/hirek',
  path: '/hirek',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentumtarRoute = DokumentumtarRouteImport.update({
  id: '/dokumentumtar',
  path: '/dokumentumtar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dokumentumtar': typeof DokumentumtarRoute
  '/hirek': typeof HirekRoute
  '/iskolankrol': typeof IskolankrolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dokumentumtar' | '/hirek' | '/iskolankrol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dokumentumtar' | '/hirek' | '/iskolankrol'
  id: '__root__' | '/' | '/dokumentumtar' | '/hirek' | '/iskolankrol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DokumentumtarRoute: typeof DokumentumtarRoute
  HirekRoute: typeof HirekRoute
  IskolankrolRoute: typeof IskolankrolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iskolankrol': {
      id: '/iskolankrol'
      path: '/iskolankrol'
      fullPath: '/iskolankrol'
      preLoaderRoute: typeof IskolankrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hirek': {
      id: '/hirek'
      path: '/hirek'
      fullPath: '/hirek'
      preLoaderRoute: typeof HirekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumentumtar': {
      id: '/dokumentumtar'
      path: '/dokumentumtar'
      fullPath: '/dokumentumtar'
      preLoaderRoute: typeof DokumentumtarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DokumentumtarRoute: DokumentumtarRoute,
  HirekRoute: HirekRoute,
  IskolankrolRoute: IskolankrolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
